# FLASH makefile definitions for ix86-64 Linux (gfortran compiler)

#----------------------------------------------------------------------------
# Set the HDF5/MPI library paths -- these need to be updated for your system
#----------------------------------------------------------------------------

# Versions > Ubuntu 24.04 / OpenMPI / HDF5 1.14

MPI_PATH   = /usr
HDF4_PATH =
  HDF5_PATH = /usr
HYPRE_PATH =
  ifeq ("$(USEOPENMP)", "1")
  HYPRE_PATH=/opt/hypre/2.8.0b_omp
endif

# Ubuntu/OpenMPI HDF5 installation
HDF5_INC   = ${MPI_PATH}/include/hdf5/openmpi
HDF5_LIB   = ${MPI_PATH}/lib/x86_64-linux-gnu/hdf5/openmpi

ZLIB_PATH  =
  
  PAPI_PATH  =
  PAPI_FLAGS =
  
  NCMPI_PATH = 
  MPE_PATH   =
  
  LAPACK_PATH = 
  
#----------------------------------------------------------------------------
# Compiler and linker commands
#
#   Use the MPICH wrappers around the compilers -- these will automatically
#   load the proper libraries and include files.  Version of MPICH prior
#   to 1.2.2 (?) do not recognize .F90 as a valid Fortran file extension.
#   You need to edit mpif90 and add .F90 to the test of filename extensions,
#   or upgrade your MPICH.
#----------------------------------------------------------------------------
  
  FCOMP   = ${MPI_PATH}/bin/mpif90
  CCOMP   = ${MPI_PATH}/bin/mpicc
  CPPCOMP = ${MPI_PATH}/bin/mpicxx
  LINK    = ${MPI_PATH}/bin/mpif90
  
# pre-processor flag
  PP      = -D
  
#----------------------------------------------------------------------------
# Compilation flags
#
#  Three sets of compilation/linking flags are defined: one for optimized
#  code, one for testing, and one for debugging.  The default is to use the
#  _OPT version.  Specifying -debug to setup will pick the _DEBUG version,
#  these should enable bounds checking.  Specifying _TEST is used for
#  flash_test, and is set for quick code generation, and (sometimes)
#  profiling.  The Makefile generated by setup will assign the generic token
#  (ex. FFLAGS) to the proper set of flags (ex. FFLAGS_OPT).
#----------------------------------------------------------------------------
  OPENMP = -fopenmp
  
  FFLAGS_OPT = -ggdb -c -O2 -fdefault-real-8 -fdefault-double-8 \
  -Wuninitialized -fallow-argument-mismatch
  
  FFLAGS_DEBUG = -ggdb -c -O0 -fdefault-real-8 -fdefault-double-8 \
  -pedantic -Waliasing                                            \
  -Wsurprising -Wconversion -Wunderflow                           \
  -ffpe-trap=invalid,zero,overflow -fbounds-check                 \
  -fimplicit-none -fstack-protector-all
  
  FFLAGS_TEST = -c -O1 -fdefault-real-8 -fdefault-double-8 \
  -fimplicit-none
  
  
  
  FFLAGS_HYPRE =
  CFLAGS_HYPRE =
  
  F90FLAGS =
  
  
#The macro _FORTIFY_SOURCE adds some lightweight checks for buffer
#overflows at both compile time and run time (only active at -O1 or higher)
#http://gcc.gnu.org/ml/gcc-patches/2004-09/msg02055.html
  CFLAGS_OPT = -ggdb -c -O2 -Wuninitialized -D_FORTIFY_SOURCE=2
  
  CFLAGS_DEBUG = -ggdb -c -Wno-div-by-zero -Wundef             \
  -D_FORTIFY_SOURCE=2                                          \
  -Wconversion -Wstrict-prototypes -Wunreachable-code          \
  -pedantic -Wall -Wextra -Winit-self -ftree-vrp -Wfloat-equal \
  -Wunsafe-loop-optimizations -Wpadded -fstack-protector-all
  
  CFLAGS_TEST = -c
  
  
# if we are using HDF5, we need to specify the path to the include files
  CFLAGS_HDF5 = -I${HDF5_INC} -DH5_USE_16_API
  CFLAGS_NCMPI = -I ${NCMPI_PATH}/include
  
  
#----------------------------------------------------------------------------
# Linker flags
#
#  There is a seperate version of the linker flags for each of the _OPT,
#  _DEBUG, and _TEST cases.
#----------------------------------------------------------------------------
  
  LFLAGS_OPT   = -ggdb -o
  LFLAGS_DEBUG = -ggdb -O0 -o
  LFLAGS_TEST  = -o
  
  
#----------------------------------------------------------------------------
# Library specific linking
#
#  If a FLASH module has a 'LIBRARY xxx' line in its Config file, we need to
#  create a macro in this Makefile.h for LIB_xxx, which will be added to the
#  link line when FLASH is built.  This allows us to switch between different
#  (incompatible) libraries.  We also create a _OPT, _DEBUG, and _TEST
#  library macro to add any performance-minded libraries (like fast math),
#  depending on how FLASH was setup.
#----------------------------------------------------------------------------
  
  LIB_OPT   =
    LIB_DEBUG =
    LIB_TEST  =
    
    LIB_HDF4  = 
    LIB_HDF5 = -L${HDF5_LIB} \
  -lhdf5hl_fortran           \
  -lhdf5_hl                  \
  -lhdf5_fortran             \
  -lhdf5                     \
  -lcrypto -lcurl -lsz -lz -ldl -lm
  
  LIB_PAPI  =
  LIB_MATH  = 
  
  LIB_MPI   = 
  LIB_NCMPI = -L $(NCMPI_PATH)/lib -lpnetcdf
  LIB_MPE   =
    LIB_HYPRE = 
    LIB_LIBNBC = -L/opt/libNBC/1.1.1/lib -lnbc
  
  LIB_LAPACK =
#----------------------------------------------------------------------------
# Additional machine-dependent object files
#
#  Add any machine specific files here -- they will be compiled and linked
#  when FLASH is built.
#----------------------------------------------------------------------------
    
    MACHOBJ =
    
    
#----------------------------------------------------------------------------
# Additional commands
#----------------------------------------------------------------------------
    
    MV = mv -f
    AR = ar -r
    RM = rm -f
    CD = cd
    RL = ranlib
    ECHO = echo
    